Update ubuntu wsl installation manual
trailofbits/algo pull request #14257
Opened 2021-07-26 18:50 UTC by jabacrack

## Description
Without this changes you get next error for git clone
```
error: chmod on /mnt/c/Users/Efsta/Code/<repo>/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.filemode' to 'false'
```

## Motivation and Context
You cannot correctly clone algo repository in WSL without this changes.

## How Has This Been Tested?
Run it in WSL several times.

## Types of changes
x Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.

2021-07-26 18:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/trailofbits/algo?pullRequest=14257) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/trailofbits/algo?pullRequest=14257) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/trailofbits/algo?pullRequest=14257) it.</sub>

2021-08-14 12:16 UTC, jackivanov commented
@jabacrack can you describe briefly what does it do please? You can add this info to the same doc file

2021-10-31 10:12 UTC, jackivanov requested changes
needs info

2022-04-27 13:23 UTC, closed without merging

2022-04-27 13:24 UTC, jabacrack commented
I close and add this pull request again - by mistake I commit with wrong credentials and cannot to sign CLA.