Use legacy OpenSSL Format on Apple Devices
trailofbits/algo pull request #14718
Opened 2024-05-06 01:09 UTC by vvorlov

## Description
Uses legacy key format to generate `.p12` and `.mobileprovision` files. 

## Motivation and Context
`openssl@3` uses a modern private key format that is unsupported on Apple devices because Apple has not updated its libraries. Importing generated `.p12` files into the modern macOS and iOS keychain leads to the wrong password error. If you try to export a private key from `.p12` and import it into Keychain separately, it will show the wrong format error. 

Closes #14558

Based on https://github.com/trailofbits/algo/pull/14622 with applied comments.

## How Has This Been Tested?

## Types of changes
Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.

2024-05-09 03:10 UTC, jackivanov requested changes

2024-05-09 03:10 UTC, jackivanov commented on roles/strongswan/tasks/openssl.yml
> +    shell: |
@vvorlov could you fix the indent please?

- https://github.com/trailofbits/algo/actions/runs/8962593883/job/24704944056?pr=14718#step:6:1435

2024-05-10 02:04 UTC, jackivanov approved these changes

2024-05-10 02:04 UTC, merged

2024-07-17 11:33 UTC, argium commented
This change has broken update-users.